In [3]:
import pandas as pd

import sys
sys.path.append('../analysis/')
from training_cluster import semi_unsupervised_KMeans
from csv_to_pandas import csv_into_dict_of_data
from constants import training_dataset, model_save_dir, wavelet_to_use


import matplotlib.pyplot as plt
%matplotlib inline

In [13]:
df_dict = csv_into_dict_of_data(training_dataset)
df = df_dict['total']

In [17]:
df.describe()

,2018-09-26,2018-11-20,2019-01-01,2018-11-18,2018-09-27,2019-01-21,2018-11-22,2019-01-11,2018-09-05,2018-11-17,...,2018-12-05,2018-11-03,2018-10-08,2019-01-19,2018-09-24,2018-11-05,2018-10-09,2018-10-06,2018-11-04,2018-09-17
count,9.600000e+01,96.000000,96.000000,96.000000,9.600000e+01,96.000000,96.000000,96.000000,9.600000e+01,96.000000,...,96.000000,96.000000,9.600000e+01,96.000000,9.600000e+01,96.000000,9.600000e+01,9.600000e+01,96.000000,9.600000e+01
mean,5.392758e+05,100518.260417,51093.666667,61758.020833,4.972231e+05,78503.229167,60756.375000,94638.250000,5.039644e+05,67046.812500,...,149691.447917,80570.239583,5.208259e+05,100890.447917,4.695609e+05,111283.666667,5.028875e+05,3.831770e+05,70843.218750,3.566238e+05
std,2.714461e+05,38552.778935,8516.686196,15790.021652,2.526288e+05,19109.939535,16701.418786,41982.759579,1.878745e+05,17916.357828,...,77584.774091,17439.066051,2.841333e+05,42212.084516,1.411981e+05,49205.816239,1.513930e+05,1.737475e+05,18827.152735,1.370626e+05
min,3.205640e+05,41459.000000,40569.000000,40757.000000,3.241240e+05,55535.000000,40525.000000,44753.000000,3.749590e+05,43019.000000,...,51159.000000,54974.000000,3.053170e+05,53039.000000,3.311390e+05,48813.000000,3.455750e+05,3.037750e+05,46323.000000,2.629590e+05
25%,3.607355e+05,67535.750000,43838.750000,51226.500000,3.655438e+05,64201.250000,47764.000000,59151.750000,3.965630e+05,54175.250000,...,64860.750000,66348.500000,3.618835e+05,62690.250000,3.753395e+05,69764.500000,3.992228e+05,3.298358e+05,56986.750000,3.007932e+05
50%,4.202555e+05,89844.500000,51416.000000,57778.000000,4.249635e+05,71761.000000,55646.000000,75798.000000,4.555380e+05,64851.000000,...,163282.000000,75399.000000,4.387690e+05,90227.000000,4.368975e+05,91670.000000,4.882580e+05,3.437925e+05,66877.500000,3.321560e+05
75%,5.751010e+05,132308.750000,53498.000000,70163.750000,5.180068e+05,90096.500000,69412.750000,126141.000000,5.203152e+05,74074.000000,...,205641.750000,93491.000000,5.258578e+05,141978.250000,5.198910e+05,150358.750000,5.709268e+05,3.711882e+05,81434.250000,3.637650e+05
max,1.601161e+06,210229.000000,85446.000000,121520.000000,1.958523e+06,162689.000000,106486.000000,189385.000000,1.389869e+06,163465.000000,...,318986.000000,135507.000000,1.833880e+06,206178.000000,1.358369e+06,274453.000000,1.401565e+06,1.588004e+06,126288.000000,1.267680e+06

In [22]:
km = semi_unsupervised_KMeans(df, 3)
yhat = km.labels_
len(yhat)

96

In [23]:
# Low = pure
# High = impure
def gini(x):
    n = len(x)
    histogram = Counter(x)
    ssp = 0
    for cnt in histogram.values():
        p=cnt/n
        ssp += p*p
    return 1-ssp